import { Diadiemkhoihanh } from '../model/diadiemkhoihanh';
export var ds_diadiemkhoihanh: Diadiemkhoihanh[] =
    [
        { "id_diadiem": 1, "OriginCode": "BINHMINH", "OriginName": "Bình Minh", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 2, "OriginCode": "BACLIEU", "OriginName": "Bạc Liêu", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 3, "OriginCode": "BAOLOC", "OriginName": "Bảo Lộc", "DestCode": "HUE", "DestName": "Huế" },
        { "id_diadiem": 4, "OriginCode": "LAMDONG", "OriginName": "Lâm Đồng", "DestCode": "HUE", "DestName": "Huế" },
        { "id_diadiem": 5, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "NHATRANG", "DestName": "Nha Trang" },
        { "id_diadiem": 6, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "DANANG", "DestName": "Đà Nẵng" },
        { "id_diadiem": 7, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "HUE", "DestName": "Huế" },
        { "id_diadiem": 8, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "NINHHOA", "DestName": "Ninh Hòa" },
        { "id_diadiem": 9, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "QUANGNGAI", "DestName": "Quảng Ngãi" },
        { "id_diadiem": 10, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "QUINHON", "DestName": "Qui Nhơn" },
        { "id_diadiem": 11, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "BINHDINH", "DestName": "Bình Định" },
        { "id_diadiem": 12, "OriginCode": "NHATRANG", "OriginName": "Nha Trang", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 13, "OriginCode": "PHANTHIET", "OriginName": "Phan Thiết", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 14, "OriginCode": "CAMAU", "OriginName": "Cà Mau", "DestCode": "CANTHO", "DestName": "Cần Thơ" },
        { "id_diadiem": 15, "OriginCode": "CAMAU", "OriginName": "Cà Mau", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 16, "OriginCode": "CANTHO", "OriginName": "Cần Thơ", "DestCode": "CAMAU", "DestName": "Cà Mau" },
        { "id_diadiem": 17, "OriginCode": "CANTHO", "OriginName": "Cần Thơ", "DestCode": "CHAUDOC", "DestName": "Châu Đốc" },
        { "id_diadiem": 18, "OriginCode": "CANTHO", "OriginName": "Cần Thơ", "DestCode": "ANGIANG", "DestName": "An Giang (Châu Đốc,Long Xuyên) " },
        { "id_diadiem": 19, "OriginCode": "CANTHO", "OriginName": "Cần Thơ", "DestCode": "DALAT", "DestName": "Đà Lạt" },
        { "id_diadiem": 20, "OriginCode": "CANTHO", "OriginName": "Cần Thơ", "DestCode": "LAMDONG", "DestName": "Lâm Đồng" },
        { "id_diadiem": 21, "OriginCode": "CANTHO", "OriginName": "Cần Thơ", "DestCode": "RACHGIA", "DestName": "Rạch Giá" },
        { "id_diadiem": 22, "OriginCode": "CANTHO", "OriginName": "Cần Thơ", "DestCode": "KIENGIANG", "DestName": "Kiên Giang" },
        { "id_diadiem": 23, "OriginCode": "CANTHO", "OriginName": "Cần Thơ", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 24, "OriginCode": "CAOLANH", "OriginName": "Cao Lãnh", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 25, "OriginCode": "DONGTHAP", "OriginName": "Đồng Tháp", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 26, "OriginCode": "CHAUDOC", "OriginName": "Châu Đốc", "DestCode": "CANTHO", "DestName": "Cần Thơ" },
        { "id_diadiem": 27, "OriginCode": "ANGIANG", "OriginName": "An Giang (Châu Đốc,Long Xuyên) ", "DestCode": "CANTHO", "DestName": "Cần Thơ" },
        { "id_diadiem": 28, "OriginCode": "CHAUDOC", "OriginName": "Châu Đốc", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 29, "OriginCode": "ANGIANG", "OriginName": "An Giang (Châu Đốc,Long Xuyên) ", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 30, "OriginCode": "DALAT", "OriginName": "Đà Lạt", "DestCode": "CANTHO", "DestName": "Cần Thơ" },
        { "id_diadiem": 31, "OriginCode": "LAMDONG", "OriginName": "Lâm Đồng", "DestCode": "CANTHO", "DestName": "Cần Thơ" },
        { "id_diadiem": 32, "OriginCode": "DALAT", "OriginName": "Đà Lạt", "DestCode": "DANANG", "DestName": "Đà Nẵng" },
        { "id_diadiem": 33, "OriginCode": "LAMDONG", "OriginName": "Lâm Đồng", "DestCode": "DANANG", "DestName": "Đà Nẵng" },
        { "id_diadiem": 34, "OriginCode": "DALAT", "OriginName": "Đà Lạt", "DestCode": "HUE", "DestName": "Huế" },
        { "id_diadiem": 35, "OriginCode": "LAMDONG", "OriginName": "Lâm Đồng", "DestCode": "HUE", "DestName": "Huế" },
        { "id_diadiem": 36, "OriginCode": "DALAT", "OriginName": "Đà Lạt", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 37, "OriginCode": "LAMDONG", "OriginName": "Lâm Đồng", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 38, "OriginCode": "DALAT", "OriginName": "Đà Lạt", "DestCode": "NHATRANG", "DestName": "Nha Trang" },
        { "id_diadiem": 39, "OriginCode": "LAMDONG", "OriginName": "Lâm Đồng", "DestCode": "NHATRANG", "DestName": "Nha Trang" },
        { "id_diadiem": 40, "OriginCode": "DANANG", "OriginName": "Đà Nẵng", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 41, "OriginCode": "DANANG", "OriginName": "Đà Nẵng", "DestCode": "DALAT", "DestName": "Đà Lạt" },
        { "id_diadiem": 42, "OriginCode": "DANANG", "OriginName": "Đà Nẵng", "DestCode": "LAMDONG", "DestName": "Lâm Đồng" },
        { "id_diadiem": 43, "OriginCode": "DANANG", "OriginName": "Đà Nẵng", "DestCode": "HANOI", "DestName": "Hà Nội" },
        { "id_diadiem": 44, "OriginCode": "DANANG", "OriginName": "Đà Nẵng", "DestCode": "NHATRANG", "DestName": "Nha Trang" },
        { "id_diadiem": 45, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "VUNGTAU", "DestName": "Vũng Tàu" },
        { "id_diadiem": 46, "OriginCode": "HANOI", "OriginName": "Hà Nội", "DestCode": "DANANG", "DestName": "Đà Nẵng" },
        { "id_diadiem": 47, "OriginCode": "HANOI", "OriginName": "Hà Nội", "DestCode": "NAMDINH", "DestName": "Nam Định" },
        { "id_diadiem": 48, "OriginCode": "HATIEN", "OriginName": "Hà Tiên", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 49, "OriginCode": "KIENGIANG", "OriginName": "Kiên Giang", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 50, "OriginCode": "HONGNGU", "OriginName": "Hồng Ngự", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 51, "OriginCode": "DONGTHAP", "OriginName": "Đồng Tháp", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 52, "OriginCode": "HUE", "OriginName": "Huế", "DestCode": "BAOLOC", "DestName": "Bảo Lộc" },
        { "id_diadiem": 53, "OriginCode": "HUE", "OriginName": "Huế", "DestCode": "LAMDONG", "DestName": "Lâm Đồng" },
        { "id_diadiem": 54, "OriginCode": "HUE", "OriginName": "Huế", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 55, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "DALAT", "DestName": "Đà Lạt" },
        { "id_diadiem": 56, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "LAMDONG", "DestName": "Lâm Đồng" },
        { "id_diadiem": 57, "OriginCode": "LONGXUYEN", "OriginName": "Long Xuyên", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 58, "OriginCode": "ANGIANG", "OriginName": "An Giang (Châu Đốc,Long Xuyên) ", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 59, "OriginCode": "MUINE", "OriginName": "Mũi Né", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 60, "OriginCode": "NAMDINH", "OriginName": "Nam Định", "DestCode": "HANOI", "DestName": "Hà Nội" },
        { "id_diadiem": 61, "OriginCode": "NHATRANG", "OriginName": "Nha Trang", "DestCode": "DALAT", "DestName": "Đà Lạt" },
        { "id_diadiem": 62, "OriginCode": "NHATRANG", "OriginName": "Nha Trang", "DestCode": "LAMDONG", "DestName": "Lâm Đồng" },
        { "id_diadiem": 63, "OriginCode": "NHATRANG", "OriginName": "Nha Trang", "DestCode": "DANANG", "DestName": "Đà Nẵng" },
        { "id_diadiem": 64, "OriginCode": "NINHHOA", "OriginName": "Ninh Hòa", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 65, "OriginCode": "QUANGNGAI", "OriginName": "Quảng Ngãi", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 66, "OriginCode": "QUINHON", "OriginName": "Qui Nhơn", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 67, "OriginCode": "BINHDINH", "OriginName": "Bình Định", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 68, "OriginCode": "RACHGIA", "OriginName": "Rạch Giá", "DestCode": "CANTHO", "DestName": "Cần Thơ" },
        { "id_diadiem": 69, "OriginCode": "KIENGIANG", "OriginName": "Kiên Giang", "DestCode": "CANTHO", "DestName": "Cần Thơ" },
        { "id_diadiem": 70, "OriginCode": "RACHGIA", "OriginName": "Rạch Giá", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 71, "OriginCode": "KIENGIANG", "OriginName": "Kiên Giang", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 72, "OriginCode": "SADEC", "OriginName": "Sa Đéc", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 73, "OriginCode": "DONGTHAP", "OriginName": "Đồng Tháp", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 74, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "TRAVINH", "DestName": "Trà Vinh" },
        { "id_diadiem": 75, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "BINHMINH", "DestName": "Bình Minh" },
        { "id_diadiem": 76, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "BACLIEU", "DestName": "Bạc Liêu" },
        { "id_diadiem": 77, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "CAMAU", "DestName": "Cà Mau" },
        { "id_diadiem": 78, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "CANTHO", "DestName": "Cần Thơ" },
        { "id_diadiem": 79, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "CAOLANH", "DestName": "Cao Lãnh" },
        { "id_diadiem": 80, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "DONGTHAP", "DestName": "Đồng Tháp" },
        { "id_diadiem": 81, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "CHAUDOC", "DestName": "Châu Đốc" },
        { "id_diadiem": 82, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "ANGIANG", "DestName": "An Giang (Châu Đốc,Long Xuyên) " },
        { "id_diadiem": 83, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "HATIEN", "DestName": "Hà Tiên" },
        { "id_diadiem": 84, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "KIENGIANG", "DestName": "Kiên Giang" },
        { "id_diadiem": 85, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "HONGNGU", "DestName": "Hồng Ngự" },
        { "id_diadiem": 86, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "DONGTHAP", "DestName": "Đồng Tháp" },
        { "id_diadiem": 87, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "LONGXUYEN", "DestName": "Long Xuyên" },
        { "id_diadiem": 88, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "ANGIANG", "DestName": "An Giang (Châu Đốc,Long Xuyên) " },
        { "id_diadiem": 89, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "MUINE", "DestName": "Mũi Né" },
        { "id_diadiem": 90, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "NHATRANG", "DestName": "Nha Trang" },
        { "id_diadiem": 91, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "RACHGIA", "DestName": "Rạch Giá" },
        { "id_diadiem": 92, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "KIENGIANG", "DestName": "Kiên Giang" },
        { "id_diadiem": 93, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "SADEC", "DestName": "Sa Đéc" },
        { "id_diadiem": 94, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "DONGTHAP", "DestName": "Đồng Tháp" },
        { "id_diadiem": 95, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "SOCTRANG", "DestName": "Sóc Trăng" },
        { "id_diadiem": 96, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "VITHANH", "DestName": "Vị Thanh" },
        { "id_diadiem": 97, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "HAUGIANG", "DestName": "Hậu Giang" },
        { "id_diadiem": 98, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "VINHLONG", "DestName": "Vĩnh Long" },
        { "id_diadiem": 99, "OriginCode": "SOCTRANG", "OriginName": "Sóc Trăng", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 100, "OriginCode": "TRAVINH", "OriginName": "Trà Vinh", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 101, "OriginCode": "VITHANH", "OriginName": "Vị Thanh", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 102, "OriginCode": "HAUGIANG", "OriginName": "Hậu Giang", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 103, "OriginCode": "VINHLONG", "OriginName": "Vĩnh Long", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 104, "OriginCode": "NHATRANG", "OriginName": "Nha Trang", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 105, "OriginCode": "VUNGTAU", "OriginName": "Vũng Tàu", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 106, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "CAMRANH", "DestName": "Cam Ranh" },
        { "id_diadiem": 107, "OriginCode": "CAMRANH", "OriginName": "Cam Ranh", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 108, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "DALAT", "DestName": "Đà Lạt" },
        { "id_diadiem": 109, "OriginCode": "HUE", "OriginName": "Huế", "DestCode": "DALAT", "DestName": "Đà Lạt" },
        { "id_diadiem": 110, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "NAMCAN", "DestName": "Năm Căn" },
        { "id_diadiem": 111, "OriginCode": "NAMCAN", "OriginName": "Năm Căn", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 112, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "CAMAU", "DestName": "Cà Mau" },
        { "id_diadiem": 113, "OriginCode": "CAMAU", "OriginName": "Cà Mau", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 114, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "VUNGTAU", "DestName": "Vũng Tàu" },
        { "id_diadiem": 115, "OriginCode": "BAOLOC", "OriginName": "Bảo Lộc", "DestCode": "DANANG", "DestName": "Đà Nẵng" },
        { "id_diadiem": 116, "OriginCode": "DANANG", "OriginName": "Đà Nẵng", "DestCode": "BAOLOC", "DestName": "Bảo Lộc" },
        { "id_diadiem": 117, "OriginCode": "DALAT", "OriginName": "Đà Lạt", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 118, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "LAMDONG", "DestName": "Lâm Đồng" },
        { "id_diadiem": 119, "OriginCode": "HATIEN", "OriginName": "Hà Tiên", "DestCode": "RACHGIA", "DestName": "Rạch Giá" },
        { "id_diadiem": 120, "OriginCode": "RACHGIA", "OriginName": "Rạch Giá", "DestCode": "HATIEN", "DestName": "Hà Tiên" },
        { "id_diadiem": 121, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "THOTNOT", "DestName": "Thốt Nốt" },
        { "id_diadiem": 122, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "CANTHO", "DestName": "Cần Thơ" },
        { "id_diadiem": 123, "OriginCode": "THOTNOT", "OriginName": "Thốt Nốt", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 124, "OriginCode": "CANTHO", "OriginName": "Cần Thơ", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 125, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "TUYHOA", "DestName": "Tuy Hòa" },
        { "id_diadiem": 126, "OriginCode": "TUYHOA", "OriginName": "Tuy Hòa", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 127, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "PHUYEN", "DestName": "Phú Yên" },
        { "id_diadiem": 128, "OriginCode": "PHUYEN", "OriginName": "Phú Yên", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 129, "OriginCode": "BENTRE", "OriginName": "Bến Tre", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 130, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "BENTRE", "DestName": "Bến Tre" },
        { "id_diadiem": 131, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "DAINGAI", "DestName": "Đại Ngãi" },
        { "id_diadiem": 132, "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "SOCTRANG", "DestName": "Sóc Trăng" },
        { "id_diadiem": 133, "OriginCode": "DAINGAI", "OriginName": "Đại Ngãi", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 134, "OriginCode": "SOCTRANG", "OriginName": "Sóc Trăng", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 135, "OriginCode": "BUONMATHUOT", "OriginName": "Buôn Ma Thuột", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 136,"OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "DALAT", "DestName": "Đà Lạt" },
        { "id_diadiem": 137,"OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "BUONMATHUOT", "DestName": "Buôn Ma Thuột" },
        { "id_diadiem": 138,"OriginCode": "DALAT", "OriginName": "Đà Lạt", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 139,"OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "DAKNONG", "DestName": "Đắk Nông" },
        { "id_diadiem": 140,"OriginCode": "DAKNONG", "OriginName": "Đắk Nông", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 141,"OriginCode": "DAKLAK", "OriginName": "Đắk Lắk", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 143,"OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "DAKLAK", "DestName": "Đắk Lắk" },
        { "id_diadiem": 142,"OriginCode": "DANANG", "OriginName": "Đà Nẵng", "DestCode": "HANOI", "DestName": "Hà Nội" },
        { "id_diadiem": 144,"OriginCode": "HANOI", "OriginName": "Hà Nội", "DestCode": "DANANG", "DestName": "Đà Nẵng" },
        { "id_diadiem": 145,"OriginCode": "DANANG", "OriginName": "Đà Nẵng", "DestCode": "CAMRANH", "DestName": "Cam Ranh" },
        { "id_diadiem": 146,"OriginCode": "CAMRANH", "OriginName": "Cam Ranh", "DestCode": "DANANG", "DestName": "Đà Nẵng" },
        { "id_diadiem": 147,"OriginCode": "VINHTHUAN", "OriginName": "Vĩnh Thuận", "DestCode": "TPHCM", "DestName": "TP. Hồ Chí Minh" },
        { "id_diadiem": 148,"OriginCode": "TPHCM", "OriginName": "TP. Hồ Chí Minh", "DestCode": "VINHTHUAN", "DestName": "Vĩnh Thuận" },
        { "id_diadiem": 149,"OriginCode": "BAOLOC", "OriginName": "Bảo Lộc", "DestCode": "QUANGNGAI", "DestName": "Quảng Ngãi" },
        { "id_diadiem": 150,"OriginCode": "QUANGNGAI", "OriginName": "Quảng Ngãi", "DestCode": "BAOLOC", "DestName": "Bảo Lộc" },
        { "id_diadiem": 151,"OriginCode": "BUONMATHUOT", "OriginName": "Buôn Ma Thuột", "DestCode": "NHATRANG", "DestName": "Nha Trang" },
        { "id_diadiem": 152,"OriginCode": "NHATRANG", "OriginName": "Nha Trang", "DestCode": "BUONMATHUOT", "DestName": "Buôn Ma Thuột" },
        { "id_diadiem": 153,"OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "DANANG", "DestName": "Đà Nẵng" },
        { "id_diadiem": 154,"OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "QUANGNGAI", "DestName": "Quảng Ngãi" },
        { "id_diadiem": 155,"OriginCode": "QUANGNGAI", "OriginName": "Quảng Ngãi", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "id_diadiem": 156,"OriginCode": "DANANG", "OriginName": "Đà Nẵng", "DestCode": "TPHCM", "DestName": "TP. Hồ Chí Minh" }]
