import { Diadiemkhoihanh } from '../model/diadiemkhoihanh';
export var ds_diadiemkhoihanh: Diadiemkhoihanh[] =
    [
        { "OriginCode": "BINHMINH", "OriginName": "Bình Minh", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "BACLIEU", "OriginName": "Bạc Liêu", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "BAOLOC", "OriginName": "Bảo Lộc", "DestCode": "HUE", "DestName": "Huế" },
        { "OriginCode": "LAMDONG", "OriginName": "Lâm Đồng", "DestCode": "HUE", "DestName": "Huế" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "NHATRANG", "DestName": "Nha Trang" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "PHANTHIET", "DestName": "Phan Thiết" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "DANANG", "DestName": "Đà Nẵng" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "HUE", "DestName": "Huế" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "NINHHOA", "DestName": "Ninh Hòa" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "QUANGNGAI", "DestName": "Quảng Ngãi" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "QUINHON", "DestName": "Qui Nhơn" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "BINHDINH", "DestName": "Bình Định" },
        { "OriginCode": "NHATRANG", "OriginName": "Nha Trang", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "PHANTHIET", "OriginName": "Phan Thiết", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "CAMAU", "OriginName": "Cà Mau", "DestCode": "CANTHO", "DestName": "Cần Thơ" },
        { "OriginCode": "CAMAU", "OriginName": "Cà Mau", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "CANTHO", "OriginName": "Cần Thơ", "DestCode": "CAMAU", "DestName": "Cà Mau" },
        { "OriginCode": "CANTHO", "OriginName": "Cần Thơ", "DestCode": "CHAUDOC", "DestName": "Châu Đốc" },
        { "OriginCode": "CANTHO", "OriginName": "Cần Thơ", "DestCode": "ANGIANG", "DestName": "An Giang (Châu Đốc,Long Xuyên) " },
        { "OriginCode": "CANTHO", "OriginName": "Cần Thơ", "DestCode": "DALAT", "DestName": "Đà Lạt" },
        { "OriginCode": "CANTHO", "OriginName": "Cần Thơ", "DestCode": "LAMDONG", "DestName": "Lâm Đồng" },
        { "OriginCode": "CANTHO", "OriginName": "Cần Thơ", "DestCode": "RACHGIA", "DestName": "Rạch Giá" },
        { "OriginCode": "CANTHO", "OriginName": "Cần Thơ", "DestCode": "KIENGIANG", "DestName": "Kiên Giang" },
        { "OriginCode": "CANTHO", "OriginName": "Cần Thơ", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "CAOLANH", "OriginName": "Cao Lãnh", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "DONGTHAP", "OriginName": "Đồng Tháp", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "CHAUDOC", "OriginName": "Châu Đốc", "DestCode": "CANTHO", "DestName": "Cần Thơ" },
        { "OriginCode": "ANGIANG", "OriginName": "An Giang (Châu Đốc,Long Xuyên) ", "DestCode": "CANTHO", "DestName": "Cần Thơ" },
        { "OriginCode": "CHAUDOC", "OriginName": "Châu Đốc", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "ANGIANG", "OriginName": "An Giang (Châu Đốc,Long Xuyên) ", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "DALAT", "OriginName": "Đà Lạt", "DestCode": "CANTHO", "DestName": "Cần Thơ" },
        { "OriginCode": "LAMDONG", "OriginName": "Lâm Đồng", "DestCode": "CANTHO", "DestName": "Cần Thơ" },
        { "OriginCode": "DALAT", "OriginName": "Đà Lạt", "DestCode": "DANANG", "DestName": "Đà Nẵng" },
        { "OriginCode": "LAMDONG", "OriginName": "Lâm Đồng", "DestCode": "DANANG", "DestName": "Đà Nẵng" },
        { "OriginCode": "DALAT", "OriginName": "Đà Lạt", "DestCode": "HUE", "DestName": "Huế" },
        { "OriginCode": "LAMDONG", "OriginName": "Lâm Đồng", "DestCode": "HUE", "DestName": "Huế" },
        { "OriginCode": "DALAT", "OriginName": "Đà Lạt", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "LAMDONG", "OriginName": "Lâm Đồng", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "DALAT", "OriginName": "Đà Lạt", "DestCode": "NHATRANG", "DestName": "Nha Trang" },
        { "OriginCode": "LAMDONG", "OriginName": "Lâm Đồng", "DestCode": "NHATRANG", "DestName": "Nha Trang" },
        { "OriginCode": "DANANG", "OriginName": "Đà Nẵng", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "DANANG", "OriginName": "Đà Nẵng", "DestCode": "DALAT", "DestName": "Đà Lạt" },
        { "OriginCode": "DANANG", "OriginName": "Đà Nẵng", "DestCode": "LAMDONG", "DestName": "Lâm Đồng" },
        { "OriginCode": "DANANG", "OriginName": "Đà Nẵng", "DestCode": "HANOI", "DestName": "Hà Nội" },
        { "OriginCode": "DANANG", "OriginName": "Đà Nẵng", "DestCode": "NHATRANG", "DestName": "Nha Trang" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "VUNGTAU", "DestName": "Vũng Tàu" },
        { "OriginCode": "HANOI", "OriginName": "Hà Nội", "DestCode": "DANANG", "DestName": "Đà Nẵng" },
        { "OriginCode": "HANOI", "OriginName": "Hà Nội", "DestCode": "NAMDINH", "DestName": "Nam Định" },
        { "OriginCode": "HATIEN", "OriginName": "Hà Tiên", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "KIENGIANG", "OriginName": "Kiên Giang", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "HONGNGU", "OriginName": "Hồng Ngự", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "DONGTHAP", "OriginName": "Đồng Tháp", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "HUE", "OriginName": "Huế", "DestCode": "BAOLOC", "DestName": "Bảo Lộc" },
        { "OriginCode": "HUE", "OriginName": "Huế", "DestCode": "LAMDONG", "DestName": "Lâm Đồng" },
        { "OriginCode": "HUE", "OriginName": "Huế", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "DALAT", "DestName": "Đà Lạt" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "LAMDONG", "DestName": "Lâm Đồng" },
        { "OriginCode": "LONGXUYEN", "OriginName": "Long Xuyên", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "ANGIANG", "OriginName": "An Giang (Châu Đốc,Long Xuyên) ", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "MUINE", "OriginName": "Mũi Né", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "NAMDINH", "OriginName": "Nam Định", "DestCode": "HANOI", "DestName": "Hà Nội" },
        { "OriginCode": "NHATRANG", "OriginName": "Nha Trang", "DestCode": "DALAT", "DestName": "Đà Lạt" },
        { "OriginCode": "NHATRANG", "OriginName": "Nha Trang", "DestCode": "LAMDONG", "DestName": "Lâm Đồng" },
        { "OriginCode": "NHATRANG", "OriginName": "Nha Trang", "DestCode": "DANANG", "DestName": "Đà Nẵng" },
        { "OriginCode": "NINHHOA", "OriginName": "Ninh Hòa", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "QUANGNGAI", "OriginName": "Quảng Ngãi", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "QUINHON", "OriginName": "Qui Nhơn", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "BINHDINH", "OriginName": "Bình Định", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "RACHGIA", "OriginName": "Rạch Giá", "DestCode": "CANTHO", "DestName": "Cần Thơ" },
        { "OriginCode": "KIENGIANG", "OriginName": "Kiên Giang", "DestCode": "CANTHO", "DestName": "Cần Thơ" },
        { "OriginCode": "RACHGIA", "OriginName": "Rạch Giá", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "KIENGIANG", "OriginName": "Kiên Giang", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "SADEC", "OriginName": "Sa Đéc", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "DONGTHAP", "OriginName": "Đồng Tháp", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "TRAVINH", "DestName": "Trà Vinh" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "BINHMINH", "DestName": "Bình Minh" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "BACLIEU", "DestName": "Bạc Liêu" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "CAMAU", "DestName": "Cà Mau" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "CANTHO", "DestName": "Cần Thơ" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "CAOLANH", "DestName": "Cao Lãnh" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "DONGTHAP", "DestName": "Đồng Tháp" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "CHAUDOC", "DestName": "Châu Đốc" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "ANGIANG", "DestName": "An Giang (Châu Đốc,Long Xuyên) " },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "HATIEN", "DestName": "Hà Tiên" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "KIENGIANG", "DestName": "Kiên Giang" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "HONGNGU", "DestName": "Hồng Ngự" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "DONGTHAP", "DestName": "Đồng Tháp" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "LONGXUYEN", "DestName": "Long Xuyên" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "ANGIANG", "DestName": "An Giang (Châu Đốc,Long Xuyên) " },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "MUINE", "DestName": "Mũi Né" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "NHATRANG", "DestName": "Nha Trang" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "RACHGIA", "DestName": "Rạch Giá" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "KIENGIANG", "DestName": "Kiên Giang" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "SADEC", "DestName": "Sa Đéc" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "DONGTHAP", "DestName": "Đồng Tháp" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "SOCTRANG", "DestName": "Sóc Trăng" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "VITHANH", "DestName": "Vị Thanh" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "HAUGIANG", "DestName": "Hậu Giang" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "VINHLONG", "DestName": "Vĩnh Long" },
        { "OriginCode": "SOCTRANG", "OriginName": "Sóc Trăng", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "TRAVINH", "OriginName": "Trà Vinh", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "VITHANH", "OriginName": "Vị Thanh", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "HAUGIANG", "OriginName": "Hậu Giang", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "VINHLONG", "OriginName": "Vĩnh Long", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "NHATRANG", "OriginName": "Nha Trang", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "VUNGTAU", "OriginName": "Vũng Tàu", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "CAMRANH", "DestName": "Cam Ranh" },
        { "OriginCode": "CAMRANH", "OriginName": "Cam Ranh", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "DALAT", "DestName": "Đà Lạt" },
        { "OriginCode": "HUE", "OriginName": "Huế", "DestCode": "DALAT", "DestName": "Đà Lạt" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "NAMCAN", "DestName": "Năm Căn" },
        { "OriginCode": "NAMCAN", "OriginName": "Năm Căn", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "CAMAU", "DestName": "Cà Mau" },
        { "OriginCode": "CAMAU", "OriginName": "Cà Mau", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "VUNGTAU", "DestName": "Vũng Tàu" },
        { "OriginCode": "BAOLOC", "OriginName": "Bảo Lộc", "DestCode": "DANANG", "DestName": "Đà Nẵng" },
        { "OriginCode": "DANANG", "OriginName": "Đà Nẵng", "DestCode": "BAOLOC", "DestName": "Bảo Lộc" },
        { "OriginCode": "DALAT", "OriginName": "Đà Lạt", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "LAMDONG", "DestName": "Lâm Đồng" },
        { "OriginCode": "HATIEN", "OriginName": "Hà Tiên", "DestCode": "RACHGIA", "DestName": "Rạch Giá" },
        { "OriginCode": "RACHGIA", "OriginName": "Rạch Giá", "DestCode": "HATIEN", "DestName": "Hà Tiên" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "THOTNOT", "DestName": "Thốt Nốt" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "CANTHO", "DestName": "Cần Thơ" },
        { "OriginCode": "THOTNOT", "OriginName": "Thốt Nốt", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "CANTHO", "OriginName": "Cần Thơ", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "TUYHOA", "DestName": "Tuy Hòa" },
        { "OriginCode": "TUYHOA", "OriginName": "Tuy Hòa", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "PHUYEN", "DestName": "Phú Yên" },
        { "OriginCode": "PHUYEN", "OriginName": "Phú Yên", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "BENTRE", "OriginName": "Bến Tre", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "BENTRE", "DestName": "Bến Tre" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "DAINGAI", "DestName": "Đại Ngãi" },
        { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "SOCTRANG", "DestName": "Sóc Trăng" },
        { "OriginCode": "DAINGAI", "OriginName": "Đại Ngãi", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "SOCTRANG", "OriginName": "Sóc Trăng", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" },
        { "OriginCode": "BUONMATHUOT", "OriginName": "Buôn Ma Thuột", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" }, { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "DALAT", "DestName": "Đà Lạt" }, { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "BUONMATHUOT", "DestName": "Buôn Ma Thuột" }, { "OriginCode": "DALAT", "OriginName": "Đà Lạt", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" }, { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "DAKNONG", "DestName": "Đắk Nông" }, { "OriginCode": "DAKNONG", "OriginName": "Đắk Nông", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" }, { "OriginCode": "DAKLAK", "OriginName": "Đắk Lắk", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" }, { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "DAKLAK", "DestName": "Đắk Lắk" }, { "OriginCode": "DANANG", "OriginName": "Đà Nẵng", "DestCode": "HANOI", "DestName": "Hà Nội" }, { "OriginCode": "HANOI", "OriginName": "Hà Nội", "DestCode": "DANANG", "DestName": "Đà Nẵng" }, { "OriginCode": "DANANG", "OriginName": "Đà Nẵng", "DestCode": "CAMRANH", "DestName": "Cam Ranh" }, { "OriginCode": "CAMRANH", "OriginName": "Cam Ranh", "DestCode": "DANANG", "DestName": "Đà Nẵng" }, { "OriginCode": "VINHTHUAN", "OriginName": "Vĩnh Thuận", "DestCode": "TPHCM", "DestName": "TP. Hồ Chí Minh" }, { "OriginCode": "TPHCM", "OriginName": "TP. Hồ Chí Minh", "DestCode": "VINHTHUAN", "DestName": "Vĩnh Thuận" }, { "OriginCode": "BAOLOC", "OriginName": "Bảo Lộc", "DestCode": "QUANGNGAI", "DestName": "Quảng Ngãi" }, { "OriginCode": "QUANGNGAI", "OriginName": "Quảng Ngãi", "DestCode": "BAOLOC", "DestName": "Bảo Lộc" }, { "OriginCode": "BUONMATHUOT", "OriginName": "Buôn Ma Thuột", "DestCode": "NHATRANG", "DestName": "Nha Trang" }, { "OriginCode": "NHATRANG", "OriginName": "Nha Trang", "DestCode": "BUONMATHUOT", "DestName": "Buôn Ma Thuột" }, { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "DANANG", "DestName": "Đà Nẵng" }, { "OriginCode": "TPHCM", "OriginName": "TP.Hồ Chí Minh", "DestCode": "QUANGNGAI", "DestName": "Quảng Ngãi" }, { "OriginCode": "QUANGNGAI", "OriginName": "Quảng Ngãi", "DestCode": "TPHCM", "DestName": "TP.Hồ Chí Minh" }, { "OriginCode": "DANANG", "OriginName": "Đà Nẵng", "DestCode": "TPHCM", "DestName": "TP. Hồ Chí Minh" }]
